# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

#trigger determines when build is run - here whenever master is changed
trigger:
- master

#pool is collection of resources, here we pull from the ubuntu pool
pool:
  vmImage: 'ubuntu-latest'

#steps - run sequencially
steps:
#tasks are prepackaged scripts - there is a task built for using node, so we don't have to write a script to install it
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

  # originally npm install and npm run build, added prefixes
- script: npm install --prefix client
  displayName: 'Install client dependencies'

- script: npm install --prefix backend
  displayName: 'Install backend dependencies'

- script: |
    npm run build
  displayName: 'Build app'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirector)'
    includeRootFolder: false

- task: AzureWebApp@1
  inputs: 
    azureSubscription: c305819f-2f31-461b-9853-0a122e2cc497
    appName: Compfitition
    package: '$(System.DefaultWorkingDirectory)'
    customWebConfig: '-Handler iisnode -NodeStartFile backend/server.js -appType node'
