# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

stages: 
- stage: Build
  displayName: Build stage
  jobs: 
  - job: Build
    displayName: Build
    pool: 
      vmImage: 'ubuntu-latest'

    steps:
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs: 
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStaginDirectory)/$(Build.BuildId).zip
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs: 
  - deployment: Deploy
    displayName: Deploy
    environment: Compfitition
    pool: 
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@4
            displayName: 'Azure App Service Deploy: Compfitition'
            inputs:
              azureSubscription: 'c305819f-2f31-461b-9853-0a122e2cc497'
              appType: webAppLinux
              WebAppName: Compfitition
              packageForLinux: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              RuntimeStack: 'NODE|10.10'
              StartupCommand: 'npm run start'
              ScriptType: 'Inline Script'
              InlineScript: |
                npm install
                npm run build