//goal types
export const GET_GOALS = 'GET_GOALS';
export const ADD_GOAL = 'ADD_GOAL';
export const DELETE_GOAL = 'DELETE_GOAL';
export const UPDATE_GOAL = 'UPDATE_GOAL';
export const UPDATE_GOAL_TRACKER = 'UPDATE_GOAL_TRACKER';
export const SET_CURRENT_GOAL = 'SET_CURRENT_GOAL';
export const CLEAR_CURRENT_GOAL = 'CLEAR_CURRENT_GOAL';
export const SET_GOAL_LOADING = 'SET_GOAL_LOADING';
export const GOAL_ERROR = 'GOAL_ERROR';
export const CLEAR_GOAL_ERRORS = 'CLEAR_GOAL_ERRORS';
export const CLEAR_GOALS = 'CLEAR_GOALS';

//auth types
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
export const UPDATE_FAIL = 'UPDATE_FAIL';
export const PASSWORD_SUCCESS = 'PASSWORD_SUCCESS';
export const PASSWORD_FAIL = 'PASSWORD_FAIL';
export const USER_DELETED_SUCCESS = 'USER_DELETED_SUCCESS';
export const USER_DELETED_FAIL = 'USER_DELETED_FAIL';
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const CLEAR_AUTH_ERRORS = 'CLEAR_AUTH_ERRORS';

//searchable users types
export const GET_SEARCHABLE_USERS = 'GET_SEARCHABLE_USERS';
export const FILTER_SEARCHABLE_USERS = 'FILTER_SEARCHABLE_USERS';
export const CLEAR_SEARCHABLE_USERS_FILTER = 'CLEAR_SEARCHABLE_USERS_FILTER';
export const SEARCHABLE_USERS_ERROR = 'SEARCHABLE_USERS_ERROR';
export const CLEAR_SEARCHABLE_USERS = 'CLEAR_SEARCHABLE_USERS';
export const CLEAR_SEARCHABLE_USERS_ERRORS = 'CLEAR_SEARCHABLE_USERS_ERRORS';

//friend types
export const GET_FRIENDS = 'GET_FRIENDS';
export const ADD_FRIEND = 'ADD_FRIEND';
export const DELETE_FRIEND = 'DELETE_FRIEND';
export const SET_CURRENT_FRIEND = 'SET_CURRENT_FRIEND';
export const GET_CURRENT_FRIEND_GOALS = 'GET_CURRENT_FRIEND_GOALS';
export const GET_CURRENT_FRIEND_FRIENDS = 'GET_CURRENT_FRIEND_FRIENDS';
export const SET_CURRENT_FRIEND_GOAL = 'SET_CURRENT_FRIEND_GOAL';
export const CLEAR_CURRENT_FRIEND = 'CLEAR_CURRENT_FRIEND';
export const SET_FRIENDS_LOADING = 'SET_FRIENDS_LOADING';
export const FRIENDS_ERROR = 'FRIENDS_ERROR';
export const CLEAR_FRIEND_ERRORS = 'CLEAR_FRIEND_ERRORS';
export const CLEAR_FRIENDS = 'CLEAR_FRIENDS';
export const FILTER_FRIENDS = 'FILTER_FRIENDS';
export const CLEAR_FRIENDS_FILTER = 'CLEAR_FRIENDS_FILTER';

//request types
export const GET_REQUESTS = 'GET_REQUESTS';
export const ADD_REQUEST = 'ADD_REQUEST';
export const DELETE_REQUEST = 'DELETE_REQUEST';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const CLEAR_REQUESTS = 'CLEAR_REQUESTS';
export const CLEAR_REQUESTS_ERROR = 'CLEAR_REQUESTS_ERROR';
export const SET_REQUESTS_LOADING = 'SET_REQUESTS_LOADING';



//competition types

//alert types
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';